"""add display symbol and isin

Revision ID: 763aa3d446c5
Revises: b64df7a1fcc8
Create Date: 2026-08-11 12:18:16.059227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763aa3d446c5'
down_revision: Union[str, Sequence[str], None] = 'b64df7a1fcc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('display_symbol', sa.String(length=50), nullable=True))
    op.add_column('stocks', sa.Column('isin', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'isin')
    op.drop_column('stocks', 'display_symbol')
    # ### end Alembic commands ###
