"""create initial tables

Revision ID: 9944d444b445
Revises: 
Create Date: 2026-08-10 15:55:51.438102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9944d444b445'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_index(op.f('ix_stocks_token'), 'stocks', ['token'], unique=True)
    op.create_table('daily_closing_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('closing_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trading_date', name='uq_stock_closing_date')
    )
    op.create_index(op.f('ix_daily_closing_prices_stock_id'), 'daily_closing_prices', ['stock_id'], unique=False)
    op.create_index(op.f('ix_daily_closing_prices_trading_date'), 'daily_closing_prices', ['trading_date'], unique=False)
    op.create_table('screened_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('trigger_time', sa.Time(), nullable=False),
    sa.Column('ltp', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('percentage_change', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screened_stocks_stock_id'), 'screened_stocks', ['stock_id'], unique=False)
    op.create_index(op.f('ix_screened_stocks_trading_date'), 'screened_stocks', ['trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screened_stocks_trading_date'), table_name='screened_stocks')
    op.drop_index(op.f('ix_screened_stocks_stock_id'), table_name='screened_stocks')
    op.drop_table('screened_stocks')
    op.drop_index(op.f('ix_daily_closing_prices_trading_date'), table_name='daily_closing_prices')
    op.drop_index(op.f('ix_daily_closing_prices_stock_id'), table_name='daily_closing_prices')
    op.drop_table('daily_closing_prices')
    op.drop_index(op.f('ix_stocks_token'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
