"""add screening events

Revision ID: b64df7a1fcc8
Revises: 9944d444b445
Create Date: 2026-08-11 11:04:35.347908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64df7a1fcc8'
down_revision: Union[str, Sequence[str], None] = '9944d444b445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=False),
    sa.Column('ltp', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('percentage_change', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_events_stock_id'), 'screening_events', ['stock_id'], unique=False)
    op.create_index(op.f('ix_screening_events_trading_date'), 'screening_events', ['trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_events_trading_date'), table_name='screening_events')
    op.drop_index(op.f('ix_screening_events_stock_id'), table_name='screening_events')
    op.drop_table('screening_events')
    # ### end Alembic commands ###
